Minor changes

diff --git a/.github/workflows/assign-community-prs.yaml b/.github/workflows/assign-community-prs.yaml
--- a/.github/workflows/assign-community-prs.yaml
+++ b/.github/workflows/assign-community-prs.yaml
@@ -17,10 +17,9 @@ jobs:
         env:
           FRONT_LINE: ${{ vars.FRONT_LINE_USERS_LIST }}
         run: |
-          if [[! -z $FRONT_LINE]]
-          then
-            echo "::error::'FRONT_LINE_USERS_LIST' environment variable is not set"
-            exit 1
+          if [[! -z $FRONT_LINE ]]; then
+          echo "::error::'FRONT_LINE_USERS_LIST' environment variable is not set"
+          exit 1
           fi
           members=($(echo $FRONT_LINE | tr ',' '\n'))
           index=$(( (${GITHUB_RUN_NUMBER}-1) % ${#members[@]} ))
