Fixes to new workflow

diff --git a/.github/workflows/monitor-issues-in-voting.yaml b/.github/workflows/monitor-issues-in-voting.yaml
--- a/.github/workflows/monitor-issues-in-voting.yaml
+++ b/.github/workflows/monitor-issues-in-voting.yaml
@@ -28,14 +28,22 @@ jobs:
     permissions:
       issues: write
     needs: select-top-voted-issue
+    env:
+      maximumVotingThreshold: ${{ vars.MAX_VOTING_THRESHOLD_DAYS }}
     steps:
+      - name: Check environment
+        run:
+          if [ -z $maximumVotingThreshold ]; then
+            echo "::error::'FRONT_LINE_USERS_LIST' environment variable is not set"
+            exit 1
+          fi
       - uses: actions/checkout@v3
+        if: success()
       - name: Close "forgotten" enhancement requests
         id: old-vote-issues
+        if: success()
         uses: actions/github-script@v6
-        env:
-          daysInterval: ${{ vars.CLOSING_ENHANCEMENTS_INTERVAL }}
         with:
           script: |
             const script = require('./.github/workflows/scripts/closeForgottenEnhancements.js')
-            await script({github, context, core})
+            await script({github, context, core, "${ env.maximumVotingThreshold }"})
